import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  receive_overlay: {
    position: "absolute",
    left: 0,
    bottom: 0,
    left: 0,
    backgroundColor: "white",
    width: "100%",
    flex: 1,
    zIndex: 10,
    elevation: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    paddingBottom: 5,
  },
  receive_head: {
    flexDirection: "row",
    display: "flex",
    width: "100%",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingTop: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderColor: "#CCC",
  },
  receive_headItem: {
    display: "flex",
    alignItems: "center",
  },
  receive_head_icon: {
    width: 40,
    height: 40,
    borderRadius: 40,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#D9D9D9",
  },
  "receive_head-txt": {
    fontSize: 16,
  },
  "receive_head-title": {
    fontSize: 14,
    marginTop: 5,
  },
  receive_headItemMid: {
    display: "flex",
    alignItems: "center",
  },
  "receive_head-title-mid": {
    fontSize: 16,
    fontFamily: "Poppins_600SemiBold",
    color: "#58BC6B",
    alignSelf: "flex-start",
  },
  "receive_head-title-mid2": {
    fontSize: 14,
    fontFamily: "Poppins_400Regular",
  },
  receive_head_icon1: {
    width: 40,
    height: 40,
    borderRadius: 40,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#126FD7",
  },
  receive_mid: {
    alignSelf: "flex-start",
    paddingHorizontal: 14,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderColor: "#CCC",
  },
  receive_mid_name: {
    fontSize: 16,
    marginBottom: 12,
  },
  receive_mid_add: {
    fontSize: 16,
  },
  receive_mid_price: {
    marginTop: 10,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  receive_mid_numb: {
    fontSize: 14,
    marginRight: 3,
  },
  receive_mid_dong: {
    fontSize: 14,
    textDecorationLine: "underline",
    marginRight: 22,
  },
  "receive_mid_status-ctn": {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 4,
    backgroundColor: "#0482F3",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  "receive_mid-txt": {
    color: "white",
    fontSize: 13,
  },
  receive_control: {
    width: "100%",
    paddingLeft: 26,
    paddingVertical: 15,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  receive_control_item: {
    display: "flex",
    alignItems: "center",
    marginRight: 35,
  },
  receive_control_circle: {
    width: 50,
    height: 50,
    borderRadius: 50,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#D9D9D9",
  },
  receive_control_txt: {
    fontSize: 14,
    marginTop: 3,
  },
  receive_btn: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  receive_btn_button: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#4FAE5A",
    borderRadius: 20,
    height: 50,
  },
  receive_btn_text: {
    fontSize: 14,
    fontFamily: "Poppins_600SemiBold",
    color: "white",
  },
  receive_btn_off: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "white",
    borderRadius: 50,
    width: 50,
    height: 50,
    borderWidth: 1,
    borderColor: "#4FAE5A",
    marginLeft: 13,
  },
});

export default styles;
