import { StyleSheet } from "react-native";
import colors from "../../styles/colors";

const styles = StyleSheet.create({
  awperson_container: {
    height: "auto",
    flex: 1,
    backgroundColor: "#F8F8F8",
  },
  awperson_banner: {
    width: "100%",
    height: 150,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  "awperson_banner-card": {
    position: "relative",
    width: "85%",
    height: 125,
    backgroundColor: "#24A69E",
    borderRadius: 22,
    shadowColor: "#000",
    shadowOffset: {
      width: -1,
      height: 3.7,
    },
    shadowOpacity: 0.12,
    shadowRadius: 20,
    elevation: 11,
    paddingLeft: 25,
    overflow: "hidden",
  },
  "awperson_banner-card-title": {
    fontSize: 22,
    textShadowOffset: {
      width: -1,
      height: 1,
    },
    textShadowOpacity: 0.9,
    textShadowRadius: 2,
    color: "#F4F900",
    fontFamily: "Poppins_600SemiBold",
    marginTop: 15,
  },
  "awperson_banner-progressbar": {
    display: "flex",
    width: 190,
    height: 5,
    backgroundColor: "rgba(228, 228, 228, 0.37)",
    borderRadius: 5,
  },
  "awperson_banner-provalue": {
    width: "80%",
    height: "100%",
    backgroundColor: "white",
    borderRadius: 5,
  },
  "awperson_banner-right": {
    display: "flex",
    width: 18,
    height: 18,
    borderRadius: 18,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
  },
  "awperson_banner-card-txt": {
    fontSize: 12,
    color: "white",
    fontFamily: "Poppins_400Regular",
    marginTop: 8,
  },
  "awperson_banner-circle1": {
    position: "absolute",
    width: 135,
    height: 135,
    borderRadius: 135,
    right: -85,
    top: -20,
  },
  "awperson_banner-circle2": {
    position: "absolute",
    width: 135,
    height: 135,
    borderRadius: 135,
    right: -30,
    bottom: -80,
  },
  awperson_award: {
    width: "100%",
    height: 95,
    backgroundColor: "white",
    padding: 16,
  },
  "awperson_award-title": {
    fontSize: 13,
    color: "#605959",
    fontFamily: "Poppins_400Regular",
    marginBottom: 5,
  },
  "awperson_award-mark": {
    fontSize: 28,
    fontFamily: "Poppins_400Regular",
  },
  "awperson_award-txt": {
    fontSize: 13,
    color: "#514C4C",
    fontFamily: "Poppins_400Regular",
    marginLeft: 5,
    marginTop: 8,
  },
  awperson_sales: {
    flex: 1,
    backgroundColor: "white",
    marginTop: 8,
    paddingLeft: 16,
  },
  "awperson_sales-title": {
    fontSize: 14,
    fontFamily: "Poppins_600SemiBold",
    marginTop: 23,
    marginBottom: 18,
  },
  "awperson_sales-item": {
    display: "flex",
    flexDirection: "row",
    height: 90,
    paddingRight: 15,
    marginBottom: 10,
  },
  "awperson_sales-item-left": {
    flex: 2,
    borderRadius: 10,
  },
  "awperson_sales-item-right": {
    flex: 2.2,
    paddingRight: 30,
    marginLeft: 14,
    borderBottomColor: "#B7A3A3",
    borderBottomWidth: 1,
  },
  "awperson_sales-right-title": {
    fontSize: 13,
    fontFamily: "Poppins_600SemiBold",
    width: 190,
  },
  "awperson_sales-right-type": {
    fontSize: 11,
    fontFamily: "Poppins_400Regular",
  },
  "awperson_sales-right-infor": {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    marginTop: 4,
    marginBottom: 5,
  },
  "awperson_sales-right-point": {
    color: "#4FAE5A",
    fontSize: 11,
    fontFamily: "Poppins_500Medium",
    marginRight: 4,
  },
  "awperson_sales-right-txt": {
    color: "rgba(93, 88, 88, 1)",
    fontSize: 11,
    fontFamily: "Poppins_500Medium",
  },
});
export default styles;
