import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  dtactivity_container: {
    flex: 1,
    backgroundColor: "#F8F8F8",
  },
  dtactivity_infor: {
    backgroundColor: "white",
    height: 78,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  dtactivity_heading: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  dtactivity_heading_txt1: {
    fontSize: 12,
    fontFamily: "Poppins_500Medium",
  },
  dtactivity_heading_txt2: {
    color: "#564949",
    fontSize: 12,
    fontFamily: "Poppins_400Regular",
  },
  dtactivity_banner: {
    backgroundColor: "#4AA054",
    display: "flex",
    flexDirection: "row",
    height: 70,
    alignItems: "center",
    paddingHorizontal: 13,
    justifyContent: "space-between",
  },
  dtactivity_banner_title1: {
    fontSize: 12,
    fontFamily: "Poppins_500Medium",
    color: "white",
    marginBottom: 6,
  },
  dtactivity_banner_title2: {
    fontSize: 10,
    fontFamily: "Poppins_300Light",
    color: "white",
  },
  dtactivity_rate:{
    height: 117,
    backgroundColor: "white",
    display: "flex",
    alignItems: "center",
    paddingTop: 16,
  },
  dtactivity_rate_title:{
    fontSize: 12,
    fontFamily: 'Poppins_600SemiBold',
  },
  dtactivity_stars:{
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    marginTop: 8,
  },
  dactivity_item: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingLeft: 18,
    paddingRight: 30,
    height: 70,
    width: "100%",
    backgroundColor: "white",
    marginBottom: 5,
    marginTop: 4,
  },
  "dactivity_item-left": {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  "dactivity_item-right": {
    display: "flex",
    marginLeft: 15,
  },
  "dactivity_item-title": {
    fontSize: 13,
    fontFamily: "Poppins_600SemiBold",
  },
  "dactivity_item-des": {
    fontSize: 11,
    fontFamily: "Poppins_400Regular",
    marginTop: 3,
  },
  dactivity_detail: {
    height: 165,
    paddingLeft: 18,
    backgroundColor: "white",
    marginBottom: 5,
  },
  dactivity_detail_title: {
    color: "#7F7373",
    fontSize: 13,
    fontFamily: "Poppins_600SemiBold",
    marginTop: 11,
    marginBottom: 16,
  },
  dactivity_detail_item: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 24,
  },
  dactivity_detail_left: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 25,
    height: 25,
    borderRadius: 25,
    backgroundColor: "#E28A22",
    position: "relative",
  },
  dactivity_line: {
    width: 24,
    height: 0,
    borderStyle: "dashed",
    borderColor: "#826e6e",
    borderTopWidth: 1,
    position: "absolute",
    transformOrigin: "0 0",
    transform: [{ rotate: "90deg" }, { scale: 1 }],
    top: -16,
  },
  dactivity_detail_right: {
    marginLeft: 13,
  },
  dactivity_detail_txt1: {
    fontSize: 9,
    fontFamily: "Poppins_300Light",
  },
  dactivity_detail_txt2: {
    fontSize: 11,
    fontFamily: "Poppins_600SemiBold",
  },
  dactivity_payment: {
    flex: 1,
    backgroundColor: "white",
    paddingLeft: 18,
    paddingRight: 15,
    paddingBottom: 32,
  },
  dactivity_payment_title: {
    color: "#7F7373",
    fontSize: 13,
    fontFamily: "Poppins_600SemiBold",
    marginTop: 11,
    marginBottom: 10,
  },
  dactivity_payment_item: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  dactivity_payment_txt: {
    fontSize: 12,
    fontFamily: "Poppins_600SemiBold",
  },
  dactivity_payment_txt1: {
    fontSize: 12,
    fontFamily: "Poppins_400Regular",
  },
  dactivity_payment_txt2: {
    display: "flex",
    flexDirection: "row",
  },
  dactivity_payment_d: {
    fontSize: 10,
    fontFamily: "Poppins_400Regular",
    textDecorationLine: "underline",
    alignSelf: "flex-end",
    marginBottom: 2,
  },
  dactivity_payment_dt: {
    fontSize: 10,
    fontFamily: "Poppins_600SemiBold",
    textDecorationLine: "underline",
    alignSelf: "flex-end",
    marginBottom: 2,
  },
});
export default styles;
