import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  custom_overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    bottom: 0,
    left: 0,
    backgroundColor: "rgba(0, 0, 0, 0.65)",
    width: "100%",
    flex: 1,
    zIndex: 10,
    elevation: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  custom_overlay_ctn: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  custom_overlay_title: {
    color: "white",
    fontSize: 18,
    fontFamily: "Poppins_400Regular",
  },
  custom_overlay_price: {
    marginTop: 19,
    fontSize: 20,
    fontFamily: "Poppins_700Bold",
    marginBottom: 19,
    color: "white",
  },
  custom_overlay_type: {
    width: "60%",
    height: 56,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "black",
  },
  "custom_overlay_type-txt": {
    fontSize: 18,
    color: "white",
    fontFamily: "Poppins_400Regular",
  },
  custom_overlay_model: {
    width: "80%",
    backgroundColor: "white",
    paddingBottom: 20,
  },
  custom_overlay_upper: {
    height: 60,
    width: "100%",
    backgroundColor: "#D9D9D9",
    display: "flex",
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-around",
  },
  "custom_overlay_upper-txt": {
    fontSize: 15,
    fontFamily: "Poppins_400Regular",
  },
  "custom_overlay_upper-txt1": {
    fontSize: 14,
    fontFamily: "Poppins_400Regular",
  },
  custom_overlay_mid: {
    width: "100%",
    paddingHorizontal: 14,
    paddingVertical: 20,
    position: "relative",
    zIndex: 12,
  },
  "custom_overlay_mid-txt": {
    fontSize: 16,
    fontFamily: "Poppins_400Regular",
    textAlign: "center",
  },
  "custom_overlay_mid-circle": {
    bottom: -15,
    left: "50%",
    position: "absolute",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 40,
    height: 40,
    backgroundColor: "black",
    borderRadius: 40,
    elevation: 10,
  },
  "custom_overlay_mid-plane": {
    transform: [{ rotate: "140deg" }],
  },
  custom_overlay_down: {
    width: "100%",
    paddingHorizontal: 14,
    paddingVertical: 20,
    backgroundColor: "#D9D9D9",
    zIndex: 8,
  },
  "custom_overlay_down-txt": {
    fontSize: 16,
    fontFamily: "Poppins_400Regular",
    textAlign: "center",
  },
  custom_overlay_btn1: {
    width: "80%",
    borderRadius: 10,
    backgroundColor: "#4FAE5A",
    height: 52,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    marginTop: 5,
  },
  "custom_overlay_btn-txt1": {
    fontSize: 15,
    fontFamily: "Poppins_600SemiBold",
    color: "white",
  },
  custom_overlay_circle: {
    position: "absolute",
    right: 23,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 40,
    height: 40,
    backgroundColor: "#3F8B48",
    borderRadius: 40,
  },
  "custom_overlay_circle-txt": {
    fontSize: 16,
    fontFamily: "Poppins_600SemiBold",
    color: "white",
    marginTop: 3,
  },
  custom_overlay_btn2: {
    width: "80%",
    borderRadius: 10,
    backgroundColor: "white",
    height: 52,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 5,
  },
  "custom_overlay_btn-txt2": {
    fontSize: 15,
    fontFamily: "Poppins_600SemiBold",
    color: "#4FAE5A",
  },
});

export default styles;
